"""Dashboard state readers — stdlib-only JSON/JSONL okuyucuları.

ARCH_GUARD Kural 1 (katman atlama yasağı): dashboard ayrı process'tir, infra
import etmez. State'e `logs/*.json|jsonl` dosyaları üzerinden erişir.

Sadece `json` ve `pathlib` kullanılır. Pydantic, infra ya da domain import YOK.

Her fonksiyon tek dosya okur, dict/list döner. Dosya yoksa veya bozuksa default.
"""
from __future__ import annotations

import json
import logging
import os
import sys
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# JSONL satır boyutu tahminleri (bytes) — tail okumada yeterli pencere için.
_BYTES_TRADES = 1000    # match_timeline dahil → geniş
_BYTES_EQUITY = 256     # küçük snapshot
_BYTES_SKIPPED = 512


# ── JSON helpers ──

def _read_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        logger.warning("Read JSON failed %s: %s", path, e)
        return default


def _read_jsonl_tail(path: Path, n: int, bytes_per_line: int) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    try:
        with open(path, "rb") as f:
            f.seek(0, 2)
            size = f.tell()
            chunk_size = min(size, n * bytes_per_line)
            f.seek(size - chunk_size)
            raw = f.read().decode("utf-8", errors="replace")
        lines = [l for l in raw.strip().split("\n") if l.strip()]
        if chunk_size < size and lines:
            lines = lines[1:]
        out: list[dict[str, Any]] = []
        for l in lines[-n:]:
            try:
                out.append(json.loads(l))
            except json.JSONDecodeError:
                continue
        return out
    except OSError as e:
        logger.warning("Read JSONL tail failed %s: %s", path, e)
        return []


# ── Public reader functions (her biri tek dosya) ──

def read_positions(logs_dir: Path) -> dict[str, Any]:
    """positions.json → {positions, realized_pnl, high_water_mark}."""
    return _read_json(logs_dir.parent / "data" / "positions.json", {"positions": {}, "realized_pnl": 0.0, "high_water_mark": 0.0})


def read_replay_simulation(logs_dir: Path) -> dict[tuple[str, str], dict[str, Any]]:
    """data/replay_simulation.json → {(condition_id, entry_timestamp): entry}.

    Returns empty dict if missing. Produced by scripts/replay_fixes_simulation.py;
    consumed by exit_events enrichment to show "if fixes had been active" P&L
    alongside each affected trade. File is regenerated by manual script run —
    bot reload/restart does not touch it (lives in data/, not session/).
    """
    blob = _read_json(logs_dir.parent / "data" / "replay_simulation.json", {})
    by_key: dict[tuple[str, str], dict[str, Any]] = {}
    for entry in blob.get("trades", []) if isinstance(blob, dict) else []:
        cid = entry.get("condition_id") or ""
        ts = entry.get("entry_timestamp") or ""
        if cid and ts:
            by_key[(cid, ts)] = entry
    return by_key




def read_trades(logs_dir: Path, n: int = 100) -> list[dict[str, Any]]:
    """Trade history — session + audit/trade_history.jsonl (current) birleşik, dedupe.

    Kaynaklar:
      - logs/session/trade_history.jsonl   (reboot mirror, reboot'ta temizlenir)
      - logs/audit/trade_history.jsonl     (kalıcı, reboot dokunmaz, ground truth)

    Arşiv dosyaları (`logs/audit/trade_history.archive.*.jsonl`) OKUNMAZ — onlar
    pre-wipe era kayıtları, mevcut realized_pnl onları içermez (bkz. startup
    reconcile GUARD-4). UI filter etmesin; dashboard kaynağı tutarlı kalsın.

    Dedupe by (condition_id, entry_timestamp): aynı kayıt iki dosyada varsa
    daha zengin exit data taşıyan kazanır. Aynı condition_id altında farklı
    entry_timestamp'li kayıtlar AYRI tutulur — bot SL sonrası re-entry yapabilir
    (sl_reentry_count), her giriş ayrı trade kaydıdır.
    """
    paths = [
        logs_dir / "session" / "trade_history.jsonl",
        logs_dir / "audit" / "trade_history.jsonl",
    ]
    by_key: dict[tuple[str, str], dict[str, Any]] = {}
    no_key: list[dict[str, Any]] = []
    for path in paths:
        if not path.exists():
            continue
        for r in _read_jsonl_tail(path, n, _BYTES_TRADES):
            cid = r.get("condition_id") or ""
            ts = r.get("entry_timestamp") or ""
            if not cid or not ts:
                no_key.append(r)
                continue
            key = (cid, ts)
            existing = by_key.get(key)
            if existing is None:
                by_key[key] = r
                continue
            new_score = (
                len(r.get("partial_exits") or []),
                int(r.get("exit_price") is not None),
            )
            ex_score = (
                len(existing.get("partial_exits") or []),
                int(existing.get("exit_price") is not None),
            )
            if new_score > ex_score:
                by_key[key] = r
    return list(by_key.values()) + no_key


def read_trades_by_month(
    logs_dir: Path, month_offset: int = 0,
) -> tuple[list[dict[str, Any]], str, bool]:
    """Calendar-month-aligned trade pagination.

    month_offset=0 → current month (1st 00:00 UTC – last day 23:59 UTC).
    month_offset=1 → previous month, etc.

    Returns (trades_in_month, month_label, has_older_data).
    """
    from datetime import datetime, timezone

    now = datetime.now(timezone.utc)
    # Target month (year, month)
    y, m = now.year, now.month
    off = month_offset
    while off > 0:
        m -= 1
        if m < 1:
            m = 12
            y -= 1
        off -= 1
    month_start = datetime(y, m, 1, 0, 0, 0, tzinfo=timezone.utc)
    # Next month (for end boundary)
    nm = m + 1
    ny = y
    if nm > 12:
        nm = 1
        ny += 1
    month_end = datetime(ny, nm, 1, 0, 0, 0, tzinfo=timezone.utc)

    buffer_months = month_offset + 2
    n = 600 * buffer_months
    all_trades = _read_jsonl_tail(logs_dir / "session" / "trade_history.jsonl", n, _BYTES_TRADES)

    month_trades: list[dict[str, Any]] = []
    has_older = False
    start_ts = month_start.isoformat()
    end_ts = month_end.isoformat()

    for t in all_trades:
        # Tam-close exit_timestamp'i + partial_exits[*].timestamp'lerini kontrol et.
        # Partial-only açık pozisyonlar düşmesin diye iki kaynak da bakılır.
        timestamps = []
        top_ts = t.get("exit_timestamp") or ""
        if top_ts:
            timestamps.append(top_ts)
        for pe in (t.get("partial_exits") or []):
            pe_ts = pe.get("timestamp") or ""
            if pe_ts:
                timestamps.append(pe_ts)
        if not timestamps:
            continue
        latest = max(timestamps)
        if latest < start_ts:
            has_older = True
        elif latest < end_ts:
            month_trades.append(t)

    _MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
               "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    label = f"{_MONTHS[m - 1]} {y}"

    return month_trades, label, has_older


def read_equity_history(logs_dir: Path, n: int = 100) -> list[dict[str, Any]]:
    """equity_history.jsonl son N snapshot — session/ (reboot'a kadar olan veriler)."""
    return _read_jsonl_tail(logs_dir / "session" / "equity_history.jsonl", n, _BYTES_EQUITY)


def read_skipped(logs_dir: Path, n: int = 100) -> list[dict[str, Any]]:
    """skipped_trades.jsonl son N skip."""
    return _read_jsonl_tail(logs_dir / "runtime" / "skipped_trades.jsonl", n, _BYTES_SKIPPED)


def read_eligible_queue(logs_dir: Path) -> list[dict[str, Any]]:
    """stock_queue.json snapshot — dashboard Stock sekmesi.

    Ad backward-compat için korundu; kaynak StockQueue.save() çıktısı.
    Dashboard'un beklediği flat schema'ya projekte edilir:
      {slug, sport_tag, question, yes_price, no_price, liquidity, volume_24h,
       match_start_iso, first_seen_iso, last_skip_reason}
    """
    raw = _read_json(logs_dir.parent / "data" / "stock_queue.json", [])
    if not isinstance(raw, list):
        return []
    flat: list[dict[str, Any]] = []
    for row in raw:
        if not isinstance(row, dict):
            continue
        market = row.get("market") or {}
        if not isinstance(market, dict):
            market = {}
        # Backward-compat: eski flat format (sadece market fields)
        if "slug" in row and "market" not in row:
            flat.append(row)
            continue
        flat.append({
            "slug": market.get("slug", ""),
            "sport_tag": market.get("sport_tag", ""),
            "question": market.get("question", ""),
            "yes_price": market.get("yes_price", 0.0),
            "no_price": market.get("no_price", 0.0),
            "liquidity": market.get("liquidity", 0.0),
            "volume_24h": market.get("volume_24h", 0.0),
            "match_start_iso": market.get("match_start_iso", ""),
            "first_seen_iso": row.get("first_seen_iso", ""),
            "last_skip_reason": row.get("last_skip_reason", ""),
        })
    return flat


def read_breaker(logs_dir: Path) -> dict[str, Any]:
    """circuit_breaker_state.json."""
    return _read_json(logs_dir.parent / "data" / "circuit_breaker_state.json", {})


def read_bot_status(logs_dir: Path) -> dict[str, Any]:
    """bot_status.json — {mode, last_cycle, last_cycle_at, reason}."""
    return _read_json(logs_dir.parent / "data" / "bot_status.json", {})


def read_balance_from_session(logs_dir: Path) -> dict[str, Any]:
    """session/equity_history.jsonl son entry'sinden balance widget metrikleri.

    Dashboard balance, realized P&L, open P&L ve peak balance hesabı için
    TEK kaynak. positions.json'a bakılmaz — reboot sonrası session silinirse
    sıfır döner (kasıtlı, audit leak koruması — test_summary_reboot_scenario).

    Returns dict with keys:
      bankroll, realized_pnl, unrealized_pnl, invested,
      open_positions, peak_bankroll (session max), has_data.
    """
    _EMPTY: dict[str, Any] = {
        "bankroll": 0.0,
        "realized_pnl": 0.0,
        "unrealized_pnl": 0.0,
        "invested": 0.0,
        "open_positions": 0,
        "peak_bankroll": 0.0,
        "has_data": False,
    }
    path = logs_dir / "session" / "equity_history.jsonl"
    if not path.exists():
        return _EMPTY

    # Son entry için tail=1; peak için tüm dosyayı okumak pahalı olabilir —
    # yeterince büyük bir pencere al (son 500 satır yeterli pratik senaryolar için).
    last_entries = _read_jsonl_tail(path, n=1, bytes_per_line=_BYTES_EQUITY)
    if not last_entries:
        return _EMPTY

    last = last_entries[-1]

    # Peak hesabı için daha geniş pencere oku.
    all_entries = _read_jsonl_tail(path, n=500, bytes_per_line=_BYTES_EQUITY)
    peak = max(
        (float(e.get("bankroll", 0.0)) for e in all_entries),
        default=float(last.get("bankroll", 0.0)),
    )

    return {
        "bankroll": float(last.get("bankroll", 0.0)),
        "realized_pnl": float(last.get("realized_pnl", 0.0)),
        "unrealized_pnl": float(last.get("unrealized_pnl", 0.0)),
        "invested": float(last.get("invested", 0.0)),
        "open_positions": int(last.get("open_positions", 0)),
        "peak_bankroll": peak,
        "has_data": True,
    }


def bot_is_alive(logs_dir: Path) -> bool:
    """agent.pid dosyasında bulunan PID hala çalışıyor mu?

    Windows: ctypes.kernel32.OpenProcess ile subprocess açmadan kontrol eder.
    POSIX: os.kill(pid, 0) güvenli existence check.
    """
    pid_file = logs_dir / "agent.pid"
    if not pid_file.exists():
        return False
    try:
        pid = int(pid_file.read_text(encoding="utf-8").strip())
    except (OSError, ValueError):
        return False
    if sys.platform == "win32":
        import ctypes
        PROCESS_QUERY_LIMITED_INFORMATION = 0x1000
        handle = ctypes.windll.kernel32.OpenProcess(
            PROCESS_QUERY_LIMITED_INFORMATION, False, pid
        )
        if not handle:
            return False
        ctypes.windll.kernel32.CloseHandle(handle)
        return True
    try:
        os.kill(pid, 0)
        return True
    except (ProcessLookupError, PermissionError, OSError):
        return False
