"""NCAA Division I Men's Basketball — full team lookup (auto-generated).

~363 D1 teams across all conferences (ACC, SEC, Big Ten, Big 12,
Big East, AAC, MWC, MAC, Atlantic 10, WCC, MVC, CAA, A-Sun, Big Sky,
Big South, Big West, Conf USA, Horizon, Ivy, MEAC, NEC, OVC,
Patriot, SoCon, Southland, Summit, Sun Belt, SWAC, WAC + Indep.).

Slug pattern: lowercase team name variants → ESPN abbreviation.
Multiple key variants per team (full name, nickname, common abbrevs).

Source: Wikipedia 2024-25 NCAA D1 conference rosters + ESPN team abbreviations.
"""

NCAAB_TEAMS: dict[str, str] = {
    # ACC (Atlantic Coast Conference) — 18 teams (post-2024 expansion)
    "duke": "DUKE", "blueDevils": "DUKE", "bluedevils": "DUKE",
    "unc": "UNC", "northcarolina": "UNC", "tarheels": "UNC", "northcarolinatarheels": "UNC",
    "ncstate": "NCST", "northcarolinastate": "NCST", "wolfpack": "NCST", "ncstatewolfpack": "NCST",
    "wake": "WAKE", "wakeforest": "WAKE", "demondeacons": "WAKE", "wakeforestdemondeacons": "WAKE",
    "uva": "UVA", "virginia": "UVA", "cavaliers": "UVA", "virginiacavaliers": "UVA", "hoos": "UVA",
    "vt": "VT", "virginiatech": "VT", "hokies": "VT", "virginiatechhokies": "VT",
    "louisville": "LOU", "cardinals": "LOU", "louisvillecardinals": "LOU",
    "pitt": "PITT", "pittsburgh": "PITT", "panthers": "PITT", "pittpanthers": "PITT",
    "syracuse": "SYR", "orange": "SYR", "syracuseorange": "SYR", "cuse": "SYR",
    "bc": "BC", "bostoncollege": "BC", "eagles": "BC", "bostoncollegeeagles": "BC",
    "miami": "MIA", "miamihurricanes": "MIA", "hurricanes": "MIA", "miamifl": "MIA",
    "fsu": "FSU", "floridastate": "FSU", "seminoles": "FSU", "floridastateseminoles": "FSU",
    "gatech": "GT", "georgiatech": "GT", "yellowjackets": "GT", "georgiatechyellowjackets": "GT",
    "clemson": "CLEM", "clemsontigers": "CLEM",
    "notredame": "ND", "fightingirish": "ND", "irish": "ND", "notredamefightingirish": "ND",
    "cal": "CAL", "california": "CAL", "goldenbears": "CAL", "californiagoldenbears": "CAL",
    "stanford": "STAN", "cardinal": "STAN", "stanfordcardinal": "STAN",
    "smu": "SMU", "southernmethodist": "SMU", "mustangs": "SMU", "smumustangs": "SMU",
    # SEC (Southeastern Conference) — 16 teams (post-2024: Texas + OU)
    "alabama": "ALA", "bama": "ALA", "crimsontide": "ALA", "alabamacrimsontide": "ALA",
    "arkansas": "ARK", "razorbacks": "ARK", "arkansasrazorbacks": "ARK", "hogs": "ARK",
    "auburn": "AUB", "auburntigers": "AUB",
    "florida": "FLA", "gators": "FLA", "floridagators": "FLA", "uf": "FLA",
    "georgia": "UGA", "bulldogs": "UGA", "georgiabulldogs": "UGA",
    "kentucky": "UK", "wildcats": "UK", "kentuckywildcats": "UK", "bigblue": "UK",
    "lsu": "LSU", "louisianastate": "LSU", "lsutigers": "LSU",
    "mississippistate": "MSST", "msstate": "MSST", "mssu": "MSST", "mississippistatebulldogs": "MSST",
    "missouri": "MIZ", "mizzou": "MIZ", "missouritigers": "MIZ",
    "olemiss": "MISS", "mississippi": "MISS", "rebels": "MISS", "olemissrebels": "MISS",
    "oklahoma": "OU", "sooners": "OU", "oklahomasooners": "OU",
    "southcarolina": "SC", "gamecocks": "SC", "southcarolinagamecocks": "SC",
    "tennessee": "TENN", "vols": "TENN", "volunteers": "TENN", "tennesseevolunteers": "TENN",
    "texas": "TEX", "longhorns": "TEX", "texaslonghorns": "TEX",
    "texasam": "TAMU", "texasaggies": "TAMU", "aggies": "TAMU", "tamu": "TAMU",
    "vanderbilt": "VAN", "commodores": "VAN", "vanderbiltcommodores": "VAN", "vandy": "VAN",
    # Big Ten — 18 teams (post-2024: Oregon, UCLA, USC, Washington)
    "illinois": "ILL", "fightingillini": "ILL", "illini": "ILL", "illinoisfightingillini": "ILL",
    "indiana": "IU", "hoosiers": "IU", "indianahoosiers": "IU",
    "iowa": "IOWA", "hawkeyes": "IOWA", "iowahawkeyes": "IOWA",
    "maryland": "MD", "terrapins": "MD", "marylandterrapins": "MD", "terps": "MD",
    "michigan": "MICH", "wolverines": "MICH", "michiganwolverines": "MICH",
    "michiganstate": "MSU", "spartans": "MSU", "michiganstatespartans": "MSU", "msu": "MSU",
    "minnesota": "MINN", "goldengophers": "MINN", "minnesotagoldengophers": "MINN", "gophers": "MINN",
    "nebraska": "NEB", "cornhuskers": "NEB", "nebraskacornhuskers": "NEB", "huskers": "NEB",
    "northwestern": "NW", "northwesternwildcats": "NW",
    "ohiostate": "OSU", "buckeyes": "OSU", "ohiostatebuckeyes": "OSU",
    "pennstate": "PSU", "nittanylions": "PSU", "pennstatenittanylions": "PSU", "psu": "PSU",
    "purdue": "PUR", "boilermakers": "PUR", "purdueboilermakers": "PUR",
    "rutgers": "RUTG", "scarletknights": "RUTG", "rutgersscarletknights": "RUTG",
    "wisconsin": "WIS", "badgers": "WIS", "wisconsinbadgers": "WIS",
    "oregon": "ORE", "ducks": "ORE", "oregonducks": "ORE",
    "ucla": "UCLA", "bruins": "UCLA", "uclabruins": "UCLA",
    "usc": "USC", "trojans": "USC", "uscstrojans": "USC", "usctrojans": "USC", "southerncalifornia": "USC",
    "washington": "WASH", "huskies": "WASH", "washingtonhuskies": "WASH", "udub": "WASH",
    # Big 12 — 16 teams (post-2024: Arizona, ASU, Colorado, Utah)
    "arizona": "ARIZ", "arizonawildcats": "ARIZ",
    "arizonastate": "ASU", "sundevils": "ASU", "arizonastatesundevils": "ASU", "asu": "ASU",
    "baylor": "BAY", "baylorbears": "BAY", "bears": "BAY",
    "byu": "BYU", "brighamyoung": "BYU", "cougars": "BYU", "byucougars": "BYU",
    "ucf": "UCF", "centralflorida": "UCF", "knights": "UCF", "ucfknights": "UCF",
    "cincinnati": "CIN", "bearcats": "CIN", "cincinnatibearcats": "CIN",
    "colorado": "COLO", "buffaloes": "COLO", "buffs": "COLO", "coloradobuffaloes": "COLO",
    "houston": "HOU", "houstoncougars": "HOU",
    "iowastate": "ISU", "cyclones": "ISU", "iowastatecyclones": "ISU",
    "kansas": "KU", "jayhawks": "KU", "kansasjayhawks": "KU",
    "kansasstate": "KSU", "ksu": "KSU", "kstate": "KSU", "kansasstatewildcats": "KSU",
    "oklahomastate": "OKST", "okstate": "OKST", "oklahomastatecowboys": "OKST", "cowboys": "OKST",
    "tcu": "TCU", "texaschristian": "TCU", "hornedfrogs": "TCU", "tcuhornedfrogs": "TCU",
    "texastech": "TTU", "redraiders": "TTU", "texastechredraiders": "TTU", "ttu": "TTU",
    "utah": "UTAH", "utes": "UTAH", "utahutes": "UTAH",
    "westvirginia": "WVU", "mountaineers": "WVU", "wvu": "WVU", "westvirginiamountaineers": "WVU",
    # Big East — 11 teams
    "uconn": "CONN", "connecticut": "CONN", "uconnhuskies": "CONN",
    "creighton": "CREI", "bluejays": "CREI", "creightonbluejays": "CREI",
    "georgetown": "GTWN", "hoyas": "GTWN", "georgetownhoyas": "GTWN",
    "marquette": "MARQ", "goldeneagles": "MARQ", "marquettegoldeneagles": "MARQ",
    "providence": "PROV", "friars": "PROV", "providencefriars": "PROV",
    "stjohns": "SJU", "redstorm": "SJU", "stjohnsredstorm": "SJU",
    "setonhall": "HALL", "pirates": "HALL", "setonhallpirates": "HALL",
    "villanova": "VILL", "wildcats_villanova": "VILL", "villanovawildcats": "VILL", "nova": "VILL",
    "xavier": "XAV", "musketeers": "XAV", "xaviermusketeers": "XAV",
    "depaul": "DEP", "depaulbluedemons": "DEP", "bluedemons": "DEP",
    "butler": "BUT", "butlerbulldogs": "BUT",
    # AAC (American Athletic Conference) — 14 teams
    "memphis": "MEM", "memphistigers": "MEM",
    "fau": "FAU", "floridaatlantic": "FAU", "owls": "FAU", "fauowls": "FAU",
    "tulane": "TULN", "greenwave": "TULN", "tulanegreenwave": "TULN",
    "wichitastate": "WICH", "shockers": "WICH", "wichitastateshockers": "WICH",
    "northtexas": "UNT", "meangreen": "UNT", "northtexasmeangreen": "UNT", "unt": "UNT",
    "charlotte": "CHAR", "fortyniners": "CHAR", "49ers": "CHAR", "charlotte49ers": "CHAR",
    "ecu": "ECU", "eastcarolina": "ECU", "eastcarolinapirates": "ECU",
    "rice": "RICE", "riceowls": "RICE",
    "temple": "TEM", "templeowls": "TEM",
    "tulsa": "TLSA", "goldenhurricane": "TLSA", "tulsagoldenhurricane": "TLSA",
    "uab": "UAB", "alabamabirmingham": "UAB", "blazers": "UAB", "uabblazers": "UAB",
    "usf": "USF", "southflorida": "USF", "southfloridabulls": "USF",
    "utsa": "UTSA", "texassanantonio": "UTSA", "roadrunners": "UTSA", "utsaroadrunners": "UTSA",
    "armywest": "ARMY", "army": "ARMY", "blackknights": "ARMY", "armyblackknights": "ARMY",
    # Mountain West (MWC) — 11 teams
    "airforce": "AFA", "falcons": "AFA", "airforcefalcons": "AFA",
    "boisestate": "BOIS", "broncos": "BOIS", "boisestatebroncos": "BOIS",
    "coloradostate": "CSU", "rams": "CSU", "coloradostaterams": "CSU",
    "fresnostate": "FRES", "bulldogs_fresno": "FRES", "fresnostatebulldogs": "FRES",
    "nevada": "NEV", "wolfpack_nevada": "NEV", "nevadawolfpack": "NEV",
    "newmexico": "UNM", "lobos": "UNM", "newmexicolobos": "UNM",
    "sandiegostate": "SDSU", "aztecs": "SDSU", "sandiegostateaztecs": "SDSU",
    "sanjosestate": "SJSU", "spartans_sjsu": "SJSU", "sanjosestatespartans": "SJSU",
    "unlv": "UNLV", "runninrebels": "UNLV", "unlvrunninrebels": "UNLV",
    "utahstate": "USU", "aggies_utahstate": "USU", "utahstateaggies": "USU",
    "wyoming": "WYO", "wyomingcowboys": "WYO",
    # WCC (West Coast Conference) — 11 teams
    "gonzaga": "GONZ", "zags": "GONZ", "bulldogs_gonzaga": "GONZ", "gonzagabulldogs": "GONZ",
    "saintmarys": "SMC", "gaels": "SMC", "saintmarysgaels": "SMC", "stmarys": "SMC",
    "sanfrancisco": "USF_WCC", "dons": "USF_WCC", "sanfranciscodons": "USF_WCC", "usfdons": "USF_WCC",
    "santaclara": "SCU", "broncos_santaclara": "SCU", "santaclarabroncos": "SCU",
    "pacific": "PAC", "tigers_pacific": "PAC", "pacifictigers": "PAC",
    "pepperdine": "PEPP", "waves": "PEPP", "pepperdinewaves": "PEPP",
    "portland": "PORT", "pilots": "PORT", "portlandpilots": "PORT",
    "lmu": "LMU", "loyolamarymount": "LMU", "lions": "LMU", "lmulions": "LMU",
    "sandiego": "USD", "toreros": "USD", "sandiegotoreros": "USD",
    "washingtonstate": "WSU", "cougars_wsu": "WSU", "washingtonstatecougars": "WSU", "wazzu": "WSU",
    "oregonstate": "ORST", "beavers": "ORST", "oregonstatebeavers": "ORST",
    # MAC (Mid-American Conference) — 12 teams
    "akron": "AKR", "zips": "AKR", "akronzips": "AKR",
    "ballstate": "BALL", "cardinals_ballstate": "BALL", "ballstatecardinals": "BALL",
    "bowlinggreen": "BGSU", "falcons_bgsu": "BGSU", "bowlinggreenfalcons": "BGSU", "bgsu": "BGSU",
    "buffalo": "BUFF", "bulls_buffalo": "BUFF", "buffalobulls": "BUFF",
    "centralmichigan": "CMU", "chippewas": "CMU", "centralmichiganchippewas": "CMU", "cmu": "CMU",
    "easternmichigan": "EMU", "eagles_emu": "EMU", "easternmichiganeagles": "EMU", "emu": "EMU",
    "kentstate": "KENT", "goldenflashes": "KENT", "kentstategoldenflashes": "KENT",
    "miamioh": "MOH", "redhawks": "MOH", "miamiohio": "MOH", "miamiredhawks": "MOH",
    "niu": "NIU", "northernillinois": "NIU", "northernillinoishuskies": "NIU",
    "ohio": "OHIO", "bobcats": "OHIO", "ohiobobcats": "OHIO",
    "toledo": "TOL", "rockets": "TOL", "toledorockets": "TOL",
    "westernmichigan": "WMU", "broncos_wmu": "WMU", "westernmichiganbroncos": "WMU", "wmu": "WMU",
    # Atlantic 10 (A-10) — 15 teams
    "davidson": "DAV", "davidsonwildcats": "DAV",
    "dayton": "DAY", "flyers": "DAY", "daytonflyers": "DAY",
    "duquesne": "DUQ", "dukes": "DUQ", "duquesnedukes": "DUQ",
    "fordham": "FORD", "rams_fordham": "FORD", "fordhamrams": "FORD",
    "georgemason": "GMU", "patriots_gmu": "GMU", "georgemasonpatriots": "GMU", "gmu": "GMU",
    "georgewashington": "GW", "revolutionaries": "GW", "gwu": "GW", "georgewashingtonrevs": "GW",
    "lasalle": "LAS", "explorers": "LAS", "lasalleexplorers": "LAS",
    "loyolachicago": "LUC", "ramblers": "LUC", "loyolachicagoramblers": "LUC",
    "umass": "MASS", "minutemen": "MASS", "massachusetts": "MASS", "umassminutemen": "MASS",
    "rhodeisland": "URI", "uri": "URI", "rams_uri": "URI", "rhodeislandrams": "URI",
    "richmond": "RICH", "spiders": "RICH", "richmondspiders": "RICH",
    "saintjoseph": "SJU_A10", "saintjoes": "SJU_A10", "hawks_sju": "SJU_A10", "stjoes": "SJU_A10", "saintjosephs": "SJU_A10",
    "saintlouis": "SLU", "billikens": "SLU", "saintlouisbillikens": "SLU", "slu": "SLU",
    "stbonaventure": "BONA", "bonnies": "BONA", "stbonaventurebonnies": "BONA",
    "vcu": "VCU", "virginiacommonwealth": "VCU", "vcurams": "VCU",
    # MVC (Missouri Valley Conference) — 12 teams
    "belmont": "BEL", "belmontbruins": "BEL",
    "bradley": "BRAD", "braves": "BRAD", "bradleybraves": "BRAD",
    "drake": "DRKE", "drakebulldogs": "DRKE",
    "evansville": "EVAN", "purpleaces": "EVAN", "evansvillepurpleaces": "EVAN",
    "illinoisstate": "ILST", "redbirds": "ILST", "illinoisstateredbirds": "ILST",
    "indianastate": "INST", "sycamores": "INST", "indianastatesycamores": "INST",
    "missouristate": "MOST", "missouristatebears": "MOST",
    "murraystate": "MUR", "racers": "MUR", "murraystateracers": "MUR",
    "northerniowa": "UNI", "panthers_uni": "UNI", "northeriniowapanthers": "UNI", "uni": "UNI",
    "southernillinois": "SIU", "salukis": "SIU", "southernillinoissalukis": "SIU",
    "uic": "UIC", "illinoischicago": "UIC", "uicflames": "UIC", "flames": "UIC",
    "valparaiso": "VAL", "beacons": "VAL", "valparaisobeacons": "VAL", "valpo": "VAL",
    # CAA (Coastal Athletic Association) — 14 teams
    "campbell": "CAMP", "fightingcamels": "CAMP", "campbellcamels": "CAMP",
    "charleston": "COFC", "collegeofcharleston": "COFC", "cougars_cofc": "COFC", "charlestoncougars": "COFC",
    "delaware": "DEL", "fightingblue": "DEL", "blue_hens": "DEL", "delawarebluehens": "DEL",
    "drexel": "DREX", "dragons": "DREX", "drexeldragons": "DREX",
    "elon": "ELON", "phoenix_elon": "ELON", "elonphoenix": "ELON",
    "hampton": "HAMP", "pirates_hampton": "HAMP", "hamptonpirates": "HAMP",
    "hofstra": "HOF", "pride": "HOF", "hofstrapride": "HOF",
    "monmouth": "MONM", "hawks_monmouth": "MONM", "monmouthhawks": "MONM",
    "ncaandt": "NCAT", "northcarolinaat": "NCAT", "aggies_ncat": "NCAT", "northcarolinaaggies": "NCAT",
    "northeastern": "NE", "huskies_ne": "NE", "northeasternhuskies": "NE",
    "stonybrook": "SBU", "seawolves": "SBU", "stonybrookseawolves": "SBU",
    "towson": "TOW", "tigers_towson": "TOW", "towsontigers": "TOW",
    "uncw": "UNCW", "uncwilmington": "UNCW", "seahawks_uncw": "UNCW", "uncwseahawks": "UNCW",
    "williammary": "WM", "william_mary": "WM", "tribe": "WM", "williammarytribe": "WM",
    # ASUN (Atlantic Sun) — 12 teams
    "austinpeay": "APSU", "governors": "APSU", "austinpeaygovernors": "APSU",
    "bellarmine": "BELL", "knights_bell": "BELL", "bellarmineknights": "BELL",
    "centralarkansas": "UCA", "uca": "UCA", "uca_bears": "UCA", "centralarkansasbears": "UCA",
    "easternkentucky": "EKU", "colonels": "EKU", "easternkentuckycolonels": "EKU",
    "fgcu": "FGCU", "floridagulfcoast": "FGCU", "eagles_fgcu": "FGCU", "fgcueagles": "FGCU",
    "jacksonville": "JU", "dolphins": "JU", "jacksonvilledolphins": "JU",
    "kennesawstate": "KENN", "owls_kenn": "KENN", "kennesawowls": "KENN",
    "libertyflames": "LIB", "liberty": "LIB", "flames_lib": "LIB", "libertyfighting": "LIB",
    "lipscomb": "LIP", "bisons": "LIP", "lipscombbisons": "LIP",
    "northalabama": "UNA", "lions_una": "UNA", "northalabamalions": "UNA",
    "northflorida": "UNF", "ospreys": "UNF", "northfloridaospreys": "UNF",
    "queens": "QUE", "queensroyals": "QUE", "royals_queens": "QUE",
    "stetson": "STET", "hatters": "STET", "stetsonhatters": "STET",
    "westgeorgia": "UWG", "uwg": "UWG", "wolves_uwg": "UWG", "westgeorgiawolves": "UWG",
    # Big Sky — 12 teams
    "easternwashington": "EWU", "eagles_ewu": "EWU", "easternwashingtoneagles": "EWU",
    "idaho": "IDHO", "vandals": "IDHO", "idahovandals": "IDHO",
    "idahostate": "IDST", "bengals": "IDST", "idahostatebengals": "IDST",
    "montana": "MONT", "grizzlies": "MONT", "montanagrizzlies": "MONT",
    "montanastate": "MTST", "bobcats_mtst": "MTST", "montanastatebobcats": "MTST",
    "northernarizona": "NAU", "lumberjacks": "NAU", "nau": "NAU", "northernarizonalumberjacks": "NAU",
    "northerncolorado": "UNCO", "unco_bears": "UNCO", "northerncoloradobears": "UNCO",
    "portlandstate": "PRST", "vikings_pdx": "PRST", "portlandstatevikings": "PRST",
    "sacramentostate": "SAC", "hornets": "SAC", "sacramentostatehornets": "SAC", "sacstate": "SAC",
    "weberstate": "WEB", "wildcats_weber": "WEB", "weberstatewildcats": "WEB",
    "fightin_ravens": "WSU_BIGSKY", "ravens_wsu": "WSU_BIGSKY",
    "ucbakersfield": "CSUB", "csubakersfield": "CSUB", "roadrunners_csub": "CSUB", "csubroadrunners": "CSUB",
    # Big South — 9 teams
    "charlestonsouthern": "CHSO", "buccaneers": "CHSO", "charlestonsouthernbucs": "CHSO",
    "gardnerwebb": "GWEB", "runninbulldogs": "GWEB", "gardnerwebbrunninbulldogs": "GWEB",
    "highpoint": "HP", "panthers_hp": "HP", "highpointpanthers": "HP",
    "longwood": "LONG", "lancers": "LONG", "longwoodlancers": "LONG",
    "presbyterian": "PRES", "bluehose": "PRES", "presbyterianbluehose": "PRES",
    "radford": "RAD", "highlanders": "RAD", "radfordhighlanders": "RAD",
    "scupstate": "USCU", "scupstatespartans": "USCU", "uscupstate": "USCU",
    "uncasheville": "UNCA", "bulldogs_unca": "UNCA", "uncashevillebulldogs": "UNCA",
    "winthrop": "WIN", "eagles_winthrop": "WIN", "winthropeagles": "WIN",
    # Big West — 11 teams
    "csufullerton": "CSUF", "titans": "CSUF", "csufullertontitans": "CSUF", "fullerton": "CSUF",
    "csunorthridge": "CSUN", "matadors": "CSUN", "csunorthridgematadors": "CSUN", "northridge": "CSUN",
    "cspomona": "CPOM", "broncos_cspomona": "CPOM",
    "hawaii": "HAW", "rainbow_warriors": "HAW", "hawaiirainbowwarriors": "HAW", "rainbows": "HAW",
    "longbeachstate": "LBSU", "thebeach": "LBSU", "longbeachstatesharks": "LBSU", "lbsu": "LBSU",
    "ucdavis": "UCD", "ucdaggies": "UCD", "ucdavisaggies": "UCD",
    "uciirvine": "UCI", "ucirvine": "UCI", "anteaters": "UCI", "ucirvineanteaters": "UCI",
    "ucriverside": "UCR", "highlanders_ucr": "UCR", "ucriversidehighlanders": "UCR",
    "ucsantabarbara": "UCSB", "gauchos": "UCSB", "ucsbgauchos": "UCSB", "ucsb": "UCSB",
    "ucsandiego": "UCSD", "tritons": "UCSD", "ucsandiegotritons": "UCSD", "ucsd": "UCSD",
    "calpoly": "CP", "calpolymustangs": "CP", "mustangs_cp": "CP",
    # Conference USA (CUSA) — 10 teams
    "fiu": "FIU", "floridainternational": "FIU", "fiupanthers": "FIU",
    "jacksonvillestate": "JVST", "gamecocks_jvst": "JVST", "jacksonvillestategamecocks": "JVST",
    "kennesaw": "KEN_CUSA",
    "liberty_cusa": "LIB_CUSA",
    "louisianatech": "LT", "louisianatechbulldogs": "LT", "bulldogs_latech": "LT",
    "mtsu": "MTSU", "middletennessee": "MTSU", "blueraiders": "MTSU", "middletennesseeblueraiders": "MTSU",
    "newmexicostate": "NMSU", "aggies_nmsu": "NMSU", "newmexicostateaggies": "NMSU",
    "samhouston": "SHSU", "bearkats": "SHSU", "samhoustonbearkats": "SHSU",
    "utep": "UTEP", "miners": "UTEP", "uteppminers": "UTEP", "utepminers": "UTEP",
    "wku": "WKU", "westernkentucky": "WKU", "hilltoppers": "WKU", "westernkentuckyhilltoppers": "WKU",
    # Horizon League — 11 teams
    "clevelandstate": "CLEV", "vikings_cle": "CLEV", "clevelandstatevikings": "CLEV",
    "detroitmercy": "DET", "titans_det": "DET", "detroitmercytitans": "DET",
    "greenbay": "GB", "wisconsingreenbay": "GB", "phoenix_gb": "GB", "greenbayphoenix": "GB",
    "iupui": "IUPUI", "jaguars_iupui": "IUPUI", "iupuijaguars": "IUPUI",
    "milwaukee": "MIL", "wisconsinmilwaukee": "MIL", "panthers_mil": "MIL", "milwaukeepanthers": "MIL",
    "northernkentucky": "NKU", "norse": "NKU", "northernkentuckynorse": "NKU", "nku": "NKU",
    "oakland": "OAK", "goldengrizzlies": "OAK", "oaklandgoldengrizzlies": "OAK",
    "purduefw": "PFW", "purduefortwayne": "PFW", "mastodons": "PFW", "purduefortwaynemastodons": "PFW",
    "robertmorris": "RMU", "colonials_rmu": "RMU", "robertmorriscolonials": "RMU",
    "wright_state": "WRST", "wrightstate": "WRST", "raiders_wright": "WRST", "wrightstateraiders": "WRST",
    "youngstownstate": "YSU", "youngstownstatepenguins": "YSU", "penguins": "YSU",
    # Ivy League — 8 teams
    "brown": "BRWN", "brownbears": "BRWN",
    "columbia": "COLU", "columbialions": "COLU", "lions_columbia": "COLU",
    "cornell": "COR", "bigred": "COR", "cornellbigred": "COR",
    "dartmouth": "DART", "biggreen": "DART", "dartmouthbiggreen": "DART",
    "harvard": "HARV", "crimson": "HARV", "harvardcrimson": "HARV",
    "penn": "PENN", "pennsylvania": "PENN", "quakers": "PENN", "pennquakers": "PENN",
    "princeton": "PRIN", "princetontigers": "PRIN",
    "yale": "YALE", "yalebulldogs": "YALE",
    # MEAC (Mid-Eastern Athletic Conference) — 8 teams
    "coppinstate": "COPP", "coppinstateeagles": "COPP",
    "delawarestate": "DSU", "delawarestatehornets": "DSU", "hornets_dsu": "DSU",
    "howard": "HOW", "bison": "HOW", "howardbison": "HOW",
    "morgan_state": "MORG", "morganstate": "MORG", "morganstatebears": "MORG",
    "ncaandtsu": "NCCU", "ncculminate": "NCCU", "northcarolinacentral": "NCCU", "ncculsf": "NCCU", "northcarolinacentraleagles": "NCCU",
    "norfolkstate": "NORF", "spartans_norf": "NORF", "norfolkstatespartans": "NORF",
    "scstate": "SCST", "southcarolinastate": "SCST", "scstatebulldogs": "SCST",
    "umes": "UMES", "marylandeasternshore": "UMES", "hawks_umes": "UMES", "umeshawks": "UMES",
    # NEC (Northeast Conference) — 8 teams
    "cccu": "CCSU", "centralconnecticut": "CCSU", "ccsublue": "CCSU", "centralconnecticutblue": "CCSU",
    "chicagostate": "CHIC", "cougars_chicago": "CHIC", "chicagostatecougars": "CHIC",
    "fdu": "FDU", "fairleighdickinson": "FDU", "fduknights": "FDU",
    "lemoyne": "LMOY", "dolphins_lemoyne": "LMOY", "lemoynedolphins": "LMOY",
    "liu": "LIU", "longislanduniversity": "LIU", "liusharks": "LIU", "sharks_liu": "LIU",
    "merrimack": "MRM", "warriors_mrm": "MRM", "merrimackwarriors": "MRM",
    "sacredheart": "SHU", "pioneers_shu": "SHU", "sacredheartpioneers": "SHU",
    "saintfrancispa": "SFPA", "stfrancispa": "SFPA", "redflash": "SFPA", "saintfrancisredflash": "SFPA",
    "stonehill": "STON", "skyhawks_stonehill": "STON", "stonehillskyhawks": "STON",
    "wagner": "WAG", "seahawks_wag": "WAG", "wagnerseahawks": "WAG",
    # OVC (Ohio Valley Conference) — 8 teams
    "easternillinois": "EIU", "panthers_eiu": "EIU", "easternillinoispanthers": "EIU",
    "littlerock": "LR", "trojans_lr": "LR", "littlerocktrojans": "LR",
    "moreheadstate": "MORE", "eagles_more": "MORE", "moreheadstateeagles": "MORE",
    "siue": "SIUE", "siuedwardsville": "SIUE", "cougars_siue": "SIUE", "siuecougars": "SIUE",
    "seiu": "SEMO", "southeastmissouri": "SEMO", "redhawks_semo": "SEMO", "southeastmissouriredhawks": "SEMO",
    "southernindiana": "USI", "screamineagles": "USI", "southernindianascreamineagles": "USI",
    "tennesseestate": "TNST", "tigers_tnst": "TNST", "tennesseestatetigers": "TNST",
    "tenntech": "TNTC", "tennesseetech": "TNTC", "goldeneagles_tt": "TNTC", "tennesseetechgoldeneagles": "TNTC",
    "uthchatt": "CHAT", "uchattanooga": "CHAT", "chattanoogamocs": "CHAT", "mocs": "CHAT",
    "westernillinois": "WIU", "leathernecks": "WIU", "westernillinoisleathernecks": "WIU",
    # Patriot League — 10 teams
    "american": "AMER", "americaneagles": "AMER", "americanuniversity": "AMER",
    "boston_university": "BU", "bostonuniversity": "BU", "terriers": "BU", "buturnpike": "BU",
    "bucknell": "BUCK", "bisons_buck": "BUCK", "bucknellbison": "BUCK",
    "colgate": "COLG", "raiders_colg": "COLG", "colgateraiders": "COLG",
    "holycross": "HC", "crusaders": "HC", "holycrosscrusaders": "HC",
    "lafayette": "LAF", "leopards": "LAF", "lafayetteleopards": "LAF",
    "lehigh": "LEH", "mountainhawks": "LEH", "lehighmountainhawks": "LEH",
    "loyolamd": "LMD", "loyolamaryland": "LMD", "greyhounds": "LMD", "loyolamarylandgreyhounds": "LMD",
    "navy": "NAVY", "midshipmen": "NAVY", "navymidshipmen": "NAVY",
    # SoCon (Southern Conference) — 10 teams
    "citadel": "CIT", "citadelbulldogs": "CIT", "thecitadel": "CIT",
    "easttennstate": "ETSU", "etsu": "ETSU", "etsubuccaneers": "ETSU", "easttennesseestate": "ETSU",
    "furman": "FUR", "paladins": "FUR", "furmanpaladins": "FUR",
    "mercer": "MER", "mercerbears": "MER",
    "samford": "SAM", "samfordbulldogs": "SAM",
    "uncgreensboro": "UNCG", "uncg": "UNCG", "uncgspartans": "UNCG", "uncgreensborospartans": "UNCG",
    "vmi": "VMI", "keydets": "VMI", "vmikeydets": "VMI", "virginiamilitary": "VMI",
    "westerncarolina": "WCU", "catamounts": "WCU", "westerncarolinacatamounts": "WCU",
    "wofford": "WOF", "woffordterriers": "WOF",
    # Southland Conference — 9 teams
    "easttexasam": "ETAM", "easttexasamlions": "ETAM",
    "houstonchristian": "HCU", "houstonchristianhuskies": "HCU", "huskies_hcu": "HCU",
    "incarnatewordcardinals": "UIW", "incarnateword": "UIW", "uiw": "UIW",
    "lamar": "LAM", "lamarcardinals": "LAM", "cardinals_lamar": "LAM",
    "mcneese": "MCNS", "cowboys_mcn": "MCNS", "mcneesecowboys": "MCNS",
    "neworleans": "UNO", "privateers": "UNO", "neworleansprivateers": "UNO",
    "nicholls": "NICH", "colonels_nich": "NICH", "nichollscolonels": "NICH",
    "northwesternstate": "NWST", "demons_nwst": "NWST", "northwesternstatedemons": "NWST",
    "seila": "SELA", "sela_lions": "SELA", "southeasternlouisiana": "SELA", "southeasternlouisianalions": "SELA",
    "texasamcc": "TAMCC", "islanders": "TAMCC", "texasamcorpuschristi": "TAMCC", "texasamcorpuschristiislanders": "TAMCC",
    # Summit League — 9 teams
    "denver": "DEN", "pioneers_den": "DEN", "denverpioneers": "DEN",
    "northdakota": "UND", "fightinghawks": "UND", "northdakotafightinghawks": "UND",
    "ndstate": "NDSU", "northdakotastate": "NDSU", "bison_ndsu": "NDSU", "northdakotastatebison": "NDSU",
    "omaha": "OMA", "mavericks_omaha": "OMA", "omahamavericks": "OMA",
    "oralroberts": "ORU", "goldeneagles_oru": "ORU", "oralrobertsgoldeneagles": "ORU",
    "stthomas": "STU", "tommies": "STU", "saintthomas": "STU", "stthomastommies": "STU",
    "southdakota": "USD_SUM", "coyotes": "USD_SUM", "southdakotacoyotes": "USD_SUM",
    "sdstate": "SDST", "southdakotastate": "SDST", "jackrabbits": "SDST", "southdakotastatejackrabbits": "SDST",
    "kansascity": "KC", "umkc": "KC", "kangaroos": "KC", "kansascityroos": "KC",
    "westernillinois_sum": "WIU_SUM",
    # Sun Belt — 14 teams
    "appalachianstate": "APP", "mountaineers_app": "APP", "appalachianstatemountaineers": "APP", "appstate": "APP",
    "arkstate": "ARST", "arkansasstate": "ARST", "redwolves": "ARST", "arkansasstateredwolves": "ARST",
    "coastalcarolina": "CCU", "chanticleers": "CCU", "coastalcarolinachanticleers": "CCU",
    "georgia_southern": "GASO", "georgiasouthern": "GASO", "eagles_gaso": "GASO", "georgiasoutherneagles": "GASO",
    "georgia_state": "GAST", "georgiastate": "GAST", "panthers_gast": "GAST", "georgiastatepanthers": "GAST",
    "jamesmadison": "JMU", "dukes_jmu": "JMU", "jamesmadisondukes": "JMU",
    "lalafayette": "ULL", "louisianalafayette": "ULL", "ragincajuns": "ULL", "louisianaragincajuns": "ULL",
    "lamonroe": "ULM", "louisianamonroe": "ULM", "warhawks": "ULM", "ulmwarhawks": "ULM",
    "marshall": "MAR", "thunderingherd": "MAR", "marshallthunderingherd": "MAR",
    "oldominion": "ODU", "monarchs": "ODU", "oldominionmonarchs": "ODU", "odu": "ODU",
    "southalabama": "USA", "jaguars_usa": "USA", "southalabamajaguars": "USA",
    "southernmiss": "USM", "goldeneagles_usm": "USM", "southernmissgoldeneagles": "USM", "southernmississippi": "USM",
    "texasstate": "TXST", "bobcats_txst": "TXST", "texasstatebobcats": "TXST",
    "troy": "TROY", "troytrojans": "TROY",
    # SWAC (Southwestern Athletic Conference) — 12 teams
    "alabamaam": "AAMU", "alabamaamuniversity": "AAMU", "bulldogs_aamu": "AAMU", "alabamaambulldogs": "AAMU",
    "alabamastate": "ALST", "hornets_alst": "ALST", "alabamastatehornets": "ALST",
    "alcornstate": "ALCN", "braves_alcn": "ALCN", "alcornstatebraves": "ALCN",
    "arkansaspb": "UAPB", "arkansaspinebluff": "UAPB", "goldenlions": "UAPB", "arkansaspbgoldenlions": "UAPB",
    "bethunecookman": "BCU", "wildcats_bcu": "BCU", "bethunecookmanwildcats": "BCU",
    "florida_am": "FAMU", "famu": "FAMU", "rattlers": "FAMU", "famurattlers": "FAMU",
    "grambling": "GRAM", "tigers_gram": "GRAM", "gramblingtigers": "GRAM",
    "jacksonstate": "JKST", "tigers_jkst": "JKST", "jacksonstatetigers": "JKST",
    "miss_valley_state": "MVSU", "missvalleystate": "MVSU", "deltadevils": "MVSU", "mississippivalleystate": "MVSU",
    "prairieview": "PV", "panthers_pv": "PV", "prairieviewpanthers": "PV",
    "southern_swac": "SOU", "southernjaguars": "SOU", "jaguars_sou": "SOU",
    "texassouthern": "TXSO", "tigers_txso": "TXSO", "texassoutherntigers": "TXSO",
    # WAC (Western Athletic Conference) — 11 teams
    "abilenechristian": "ACU", "wildcats_acu": "ACU", "abilenechristianwildcats": "ACU",
    "californiabaptist": "CBU", "cbu": "CBU", "lancers_cbu": "CBU", "californiabaptistlancers": "CBU",
    "grandcanyon": "GCU", "antelopes": "GCU", "grandcanyonantelopes": "GCU", "lopes": "GCU",
    "seattleu": "SEA", "redhawks_seattle": "SEA", "seattleuredhawks": "SEA",
    "tarleton": "TARL", "texansttarleton": "TARL", "tarletontexans": "TARL",
    "utahtech": "UT_TECH", "utahtechtrailblazers": "UT_TECH", "trailblazers_ut": "UT_TECH",
    "uttrgv": "UTRGV", "utrgv": "UTRGV", "vaqueros": "UTRGV", "uttrgvvaqueros": "UTRGV",
    "uvu": "UVU", "utahvalley": "UVU", "wolverines_uvu": "UVU", "utahvalleywolverines": "UVU",
    # D1 Independents — 2 teams
    "chigaco": "CHIC_IND",
    "lindenwood": "LIN", "lindenwoodlions": "LIN",
    # Aliases / common ESPN slug forms
    "uconnhuskies_ncaa": "CONN",
    "northcarolinaagt": "NCAT",
    "marylandeastshore": "UMES",
    "saintmaryscaa": "SMC",
    "kentstategoldflashes": "KENT",
}
