"""WNCAAB lookup pt1 — ACC / SEC / Big Ten ... Big West (Power + AAC + Mid-major P1).

Bölünme nedeni: ARCH_GUARD §3 (max 400 satır). _wncaab_teams.py'a merge edilir.
"""
from __future__ import annotations


WNCAAB_TEAMS_P1: dict[str, str] = {
    # ACC (Atlantic Coast Conference) - 18 women's teams
    "bc": "BC", "bostoncollege": "BC", "eagles": "BC",
    "cal": "CAL", "california": "CAL", "goldenbears": "CAL",
    "clem": "CLEM", "clemson": "CLEM", "tigers": "CLEM",
    "duke": "DUKE", "bluedevils": "DUKE",
    "fsu": "FSU", "floridastate": "FSU", "seminoles": "FSU",
    "gt": "GT", "georgiatech": "GT", "yellowjackets": "GT",
    "lou": "LOU", "louisville": "LOU", "cardinals": "LOU",
    "miami": "MIA", "miamifl": "MIA", "hurricanes": "MIA",
    "unc": "UNC", "northcarolina": "UNC", "tarheels": "UNC",
    "ncst": "NCST", "ncstate": "NCST", "wolfpack": "NCST",
    "nd": "ND", "notredame": "ND", "fightingirish": "ND",
    "pitt": "PITT", "pittsburgh": "PITT", "panthers": "PITT",
    "smu": "SMU", "mustangs": "SMU",
    "stan": "STAN", "stanford": "STAN", "cardinal": "STAN",
    "syr": "SYR", "syracuse": "SYR", "orange": "SYR",
    "uva": "UVA", "virginia": "UVA", "cavaliers": "UVA",
    "vt": "VT", "virginiatech": "VT", "hokies": "VT",
    "wake": "WAKE", "wakeforest": "WAKE", "demondeacons": "WAKE",

    # SEC (Southeastern Conference) - 16 women's teams
    "ala": "ALA", "alabama": "ALA", "crimsontide": "ALA",
    "ark": "ARK", "arkansas": "ARK", "razorbacks": "ARK",
    "aub": "AUB", "auburn": "AUB", "auburntigers": "AUB",
    "uf": "UF", "florida": "UF", "gators": "UF",
    "uga": "UGA", "georgia": "UGA", "ladybulldogs": "UGA",
    "uk": "UK", "kentucky": "UK", "ladycats": "UK", "wildcats": "UK",
    "lsu": "LSU", "louisianastate": "LSU", "ladytigers": "LSU",
    "miss": "MISS", "olemiss": "MISS", "mississippi": "MISS", "rebels": "MISS",
    "msst": "MSST", "missst": "MSST", "missstate": "MSST", "mississippistate": "MSST",
    "mizz": "MIZZ", "missouri": "MIZZ",
    "okla": "OKLA", "oklahoma": "OKLA", "sooners": "OKLA",
    "sc": "SC", "southcarolina": "SC", "gamecocks": "SC",
    "tenn": "TENN", "tennessee": "TENN", "ladyvols": "TENN", "volunteers": "TENN",
    "tex": "TEX", "texas": "TEX", "longhorns": "TEX",
    "tama": "TAMA", "texasam": "TAMA", "aggies": "TAMA",
    "vandy": "VANDY", "vanderbilt": "VANDY", "commodores": "VANDY",

    # Big Ten - 18 women's teams
    "ill": "ILL", "illinois": "ILL", "fightingillini": "ILL",
    "ind": "IND", "indiana": "IND", "hoosiers": "IND",
    "iowa": "IOWA", "hawkeyes": "IOWA",
    "md": "MD", "maryland": "MD", "terrapins": "MD", "terps": "MD",
    "mich": "MICH", "michigan": "MICH", "wolverines": "MICH",
    "msu": "MSU", "michiganstate": "MSU", "spartans": "MSU",
    "minn": "MINN", "minnesota": "MINN", "golphers": "MINN", "gophers": "MINN",
    "neb": "NEB", "nebraska": "NEB", "huskers": "NEB", "cornhuskers": "NEB",
    "nu": "NU", "northwestern": "NU",
    "osu": "OSU", "ohiostate": "OSU", "buckeyes": "OSU",
    "oregon": "ORE", "ducks": "ORE", "ore": "ORE",
    "psu": "PSU", "pennstate": "PSU", "nittanylions": "PSU",
    "pur": "PUR", "purdue": "PUR", "boilermakers": "PUR",
    "rut": "RUT", "rutgers": "RUT", "scarletknights": "RUT",
    "ucla": "UCLA", "bruins": "UCLA",
    "usc": "USC", "southerncal": "USC", "trojans": "USC",
    "wash": "WASH", "washington": "WASH", "huskies": "WASH",
    "wis": "WIS", "wisc": "WIS", "wisconsin": "WIS", "badgers": "WIS",

    # Big 12 - 16 women's teams
    "ariz": "ARIZ", "arizona": "ARIZ", "ariza": "ARIZ",
    "asu": "ASU", "arizonastate": "ASU", "sundevils": "ASU",
    "bay": "BAY", "baylor": "BAY", "ladybears": "BAY",
    "byu": "BYU", "brighamyoung": "BYU", "cougars": "BYU",
    "cin": "CIN", "cincinnati": "CIN", "bearcats": "CIN",
    "colo": "COLO", "colorado": "COLO", "buffaloes": "COLO", "buffs": "COLO",
    "hou": "HOU", "houston": "HOU", "houstoncougars": "HOU",
    "isu": "ISU", "iowastate": "ISU", "cyclones": "ISU",
    "ku": "KU", "kansas": "KU", "jayhawks": "KU",
    "ksu": "KSU", "kansasstate": "KSU", "kstate": "KSU",
    "okst": "OKST", "oklahomastate": "OKST", "cowgirls": "OKST",
    "tcu": "TCU", "texaschristian": "TCU", "hornedfrogs": "TCU",
    "ttu": "TTU", "texastech": "TTU", "ladyraiders": "TTU", "redraiders": "TTU",
    "ucf": "UCF", "centralflorida": "UCF", "knights": "UCF",
    "utah": "UTAH", "utes": "UTAH",
    "wvu": "WVU", "westvirginia": "WVU", "mountaineers": "WVU",

    # Big East - 11 women's teams
    "but": "BUT", "butler": "BUT", "butlerbulldogs": "BUT",
    "crei": "CREI", "creighton": "CREI", "bluejays": "CREI",
    "depaul": "DEP", "dep": "DEP", "bluedemons": "DEP",
    "geo": "GEO", "georgetown": "GEO", "hoyas": "GEO",
    "mar": "MAR", "marquette": "MAR", "goldeneagles": "MAR",
    "prov": "PROV", "providence": "PROV", "friars": "PROV",
    "sjf": "STJ", "stj": "STJ", "stjohns": "STJ", "redstorm": "STJ",
    "set": "SET", "setonhall": "SET", "pirates": "SET",
    "uconn": "CONN", "conn": "CONN", "connecticut": "CONN", "ladyhuskies": "CONN",
    "vill": "VILL", "villanova": "VILL", "novawildcats": "VILL",
    "xav": "XAV", "xavier": "XAV", "musketeers": "XAV",

    # AAC (American Athletic) - 14 women's teams
    "char": "CHAR", "charlotte": "CHAR", "fortyniners": "CHAR", "49ers": "CHAR",
    "ecu": "ECU", "eastcarolina": "ECU", "pirateseast": "ECU",
    "fau": "FAU", "floridaatlantic": "FAU", "owls": "FAU",
    "memph": "MEMPH", "memphis": "MEMPH",
    "navy": "NAVY", "midshipmen": "NAVY",
    "rice": "RICE", "owlsrice": "RICE",
    "smumustangs": "SMU2",
    "usf": "USF", "southflorida": "USF", "bulls": "USF",
    "temp": "TEMP", "temple": "TEMP",
    "tulane": "TUL", "greenwave": "TUL",
    "tulsa": "TULS", "goldenhurricane": "TULSA",
    "uab": "UAB", "alabamabirmingham": "UAB", "blazers": "UAB",
    "utsa": "UTSA", "texassanantonio": "UTSA", "roadrunners": "UTSA",
    "wich": "WICH", "wichita": "WICH", "wichitastate": "WICH", "shockers": "WICH",

    # Mountain West - 11 women's teams
    "afa": "AF", "airforce": "AF", "falcons": "AF",
    "bsu": "BSU", "boisestate": "BSU", "broncos": "BSU",
    "cstate": "CSU", "coloradostate": "CSU", "rams": "CSU",
    "fres": "FRES", "fresno": "FRES", "fresnostate": "FRES", "bulldogs": "FRES",
    "nev": "NEV", "nevada": "NEV", "wolfpacknev": "NEV",
    "nmsl": "NM", "newmexico": "NM", "lobos": "NM",
    "sdsu": "SDSU", "sandiegostate": "SDSU", "aztecs": "SDSU",
    "sjsu": "SJSU", "sanjosestate": "SJSU", "spartansjsu": "SJSU",
    "unlv": "UNLV", "unlasvegas": "UNLV", "runninrebels": "UNLV",
    "utst": "USU", "utahstate": "USU", "aggiesusu": "USU",
    "wyo": "WYO", "wyoming": "WYO", "wyocowgirls": "WYO",

    # MAC (Mid-American) - 12 women's teams
    "akr": "AKR", "akron": "AKR", "zips": "AKR",
    "bgsu": "BGSU", "bowlinggreen": "BGSU", "bgsufalcons": "BGSU",
    "ball": "BALL", "ballstate": "BALL", "ballstatecards": "BALL",
    "buf": "BUF", "buffalo": "BUF", "bulldogs2": "BUF",
    "cmu": "CMU", "centralmichigan": "CMU", "chippewas": "CMU",
    "emu": "EMU", "easternmichigan": "EMU", "eagles2": "EMU",
    "kent": "KENT", "kentstate": "KENT", "goldenflashes": "KENT",
    "miohio": "MOH", "miamiohio": "MOH", "redhawks": "MOH",
    "niu": "NIU", "northernillinois": "NIU", "niuhuskies": "NIU",
    "ohio": "OHIO", "bobcats": "OHIO",
    "tol": "TOL", "toledo": "TOL", "rockets2": "TOL",
    "wmu": "WMU", "westernmichigan": "WMU", "wmubroncos": "WMU",

    # Atlantic 10 - 15 women's teams
    "davids": "DAV", "davidson": "DAV", "wildcats2": "DAV",
    "day": "DAY", "dayton": "DAY", "flyers": "DAY",
    "duq": "DUQ", "duquesne": "DUQ", "dukes": "DUQ",
    "ford": "FORD", "fordham": "FORD", "fordhamrams": "FORD",
    "gmu": "GMU", "georgemason": "GMU", "patriots": "GMU",
    "gw": "GW", "georgewashington": "GW", "colonials": "GW",
    "lasalle": "LSL", "explorers": "LSL",
    "loyola": "LOY", "loyolachicago": "LOY", "ramblers": "LOY",
    "umass": "MASS", "massachusetts": "MASS", "minutewomen": "MASS",
    "rich": "RICH", "richmond": "RICH", "spiders": "RICH",
    "slu": "SLU", "stlouis": "SLU", "billikens": "SLU",
    "sbon": "SB", "stbonaventure": "SB", "bonnies": "SB",
    "stjoes": "SJU", "stjoseph": "SJU", "hawks2": "SJU",
    "vcu": "VCU", "virginiacommonwealth": "VCU", "ramsvcu": "VCU",
    "udel": "DEL", "delaware": "DEL", "delawarefightinblue": "DEL",

    # Conference USA (CUSA) - 9 women's teams
    "ftlib": "LIB", "liberty": "LIB", "flames": "LIB",
    "ftrk": "MTSU", "middletenn": "MTSU", "middletennessee": "MTSU", "blueraiders": "MTSU",
    "ftbire": "WKU", "westernkentucky": "WKU", "hilltoppers": "WKU",
    "ftcusa1": "LA", "louisianatech": "LA", "ladytechsters": "LA",
    "jvst": "JVST", "jacksonvillestate": "JVST", "ladygamecocks": "JVST",
    "nmst": "NMSU", "newmexicostate": "NMSU", "aggies2": "NMSU",
    "sam": "SHSU", "samhouston": "SHSU", "bearkats": "SHSU",
    "uts": "TXST", "texasstate": "TXST", "bobcats2": "TXST",
    "wkust": "WKU2", "ftcwh": "FIU", "floridainternational": "FIU", "panthers2": "FIU",

    # Sun Belt - 14 women's teams
    "appst": "APP", "appalachian": "APP", "appstate": "APP", "appalachianstate": "APP", "mountaineers2": "APP",
    "arst": "ARST", "arkst": "ARST", "arkansasstate": "ARST", "redwolves": "ARST",
    "ccu": "CCU", "coastalcarolina": "CCU", "chants": "CCU", "chanticleers": "CCU",
    "gasou": "GASO", "georgiasouthern": "GASO", "geosouthern": "GASO",
    "gast": "GAST", "georgiastate": "GAST", "panthers3": "GAST",
    "jmu": "JMU", "jamesmadison": "JMU", "duke3": "JMU",
    "lala": "ULL", "louisianalafayette": "ULL", "ragincajuns": "ULL",
    "ulmonroe": "ULM", "louisianamonroe": "ULM", "warhawks": "ULM",
    "marshall": "MAR2", "thunderingherd": "MAR2",
    "ode": "ODU", "oldominion": "ODU", "monarchs": "ODU",
    "sou": "SOU", "southalabama": "SOU", "jaguarssou": "SOU",
    "smiss": "USM", "southernmiss": "USM", "goldeneagles2": "USM",
    "trsu": "TROY", "troy": "TROY", "trojans2": "TROY",
    "txst2": "TXSTATE", "texstate2": "TXSTATE",

    # WCC (West Coast) - 11 women's teams
    "gonz": "GONZ", "gonzaga": "GONZ", "zags": "GONZ",
    "lmu": "LMU", "loyolamarymount": "LMU", "lions": "LMU",
    "pacif": "PAC", "pacific": "PAC", "tigers2": "PAC",
    "pep": "PEP", "pepperdine": "PEP", "waves": "PEP",
    "port": "POR", "portland": "POR", "pilots": "POR",
    "smc": "SMC", "stmarys": "SMC", "gaelssmc": "SMC",
    "sf": "SF", "sanfrancisco": "SF", "dons": "SF",
    "scu": "SCU", "santaclara": "SCU", "broncos2": "SCU",
    "sd": "SDC", "sandiego": "SDC", "toreros": "SDC",
    "byucougs": "BYUW", "wccbyu": "BYUW",
    "seattle": "SEA", "redhawks2": "SEA",

    # Big Sky - 10 women's teams
    "easstwa": "EWU", "easternwa": "EWU", "easternwashington": "EWU",
    "ida": "IDA", "idaho": "IDA", "vandals": "IDA",
    "idst": "IDST", "idahost": "IDST", "idahostate": "IDST", "bengals": "IDST",
    "mont": "MONT", "montana": "MONT", "grizzlies": "MONT",
    "monst": "MTST", "montanast": "MTST", "montanastate": "MTST", "bobcats3": "MTST",
    "naue": "NAU", "northernaz": "NAU", "lumberjacks": "NAU",
    "nco": "NCO", "ncolo": "NCO", "northerncolorado": "NCO", "bears2": "NCO",
    "psue": "PSUE", "portlandst": "PSUE", "vikings": "PSUE",
    "sue": "SAC", "sacstate": "SAC", "hornets2": "SAC",
    "wsu": "WSU", "weberstate": "WSU", "wildcats3": "WSU",

    # Big South - 9 women's teams
    "campbel": "CAMP", "campbell": "CAMP", "fightingcamels": "CAMP",
    "chsou": "CHSO", "charlestonsou": "CHSO", "charlestonsouthern": "CHSO", "buccaneers": "CHSO",
    "gar": "GAR", "gardnerwebb": "GAR", "runninbulldogs": "GAR",
    "high": "HIGH", "highpoint": "HIGH", "highpointpanthers": "HIGH",
    "long": "LONG", "longwood": "LONG", "lancers": "LONG",
    "presby": "PRES", "presbyterian": "PRES", "blueose": "PRES", "bluehose": "PRES",
    "radford": "RAD", "highlanders": "RAD",
    "uncasheville": "UNCA", "uncavl": "UNCA", "bulldogsasheville": "UNCA",
    "wincarsj": "WCU", "winthropchanced": "WCU",

    # Big West - 11 women's teams
    "csub": "CSUB", "csubakers": "CSUB", "csubakersfield": "CSUB", "roadrunners2": "CSUB",
    "csuf": "CSUF", "csufullerton": "CSUF", "csutitans": "CSUF",
    "csun": "CSUN", "csunorthridge": "CSUN", "matadors": "CSUN",
    "ham": "HAW", "hawaii": "HAW", "rainbowwahine": "HAW",
    "lbsu": "LBSU", "longbeach": "LBSU", "longbeachst": "LBSU", "thebeach": "LBSU",
    "ucd": "UCD", "ucdavis": "UCD", "ucdaggies": "UCD",
    "uci": "UCI", "ucirvine": "UCI", "anteaters": "UCI",
    "ucr": "UCR", "ucriverside": "UCR", "ucrhighlanders": "UCR",
    "ucsd": "UCSD", "ucsandiego": "UCSD", "tritons": "UCSD",
    "ucsb": "UCSB", "ucsantabarbara": "UCSB", "gauchos": "UCSB",
    "uop": "UOP", "uopacific": "UOP",

}
