"""NCAA Division I Women's Basketball — full team lookup (auto-generated).

~351 D1 women's teams across all conferences (2024-25 season).
Slug pattern: lowercase team name variants -> ESPN abbreviation.
Multiple key variants per team (full name, nickname, common abbrevs).

Saf domain — I/O yok, sabit lookup tablosu.
"""
from __future__ import annotations


WNCAAB_TEAMS: dict[str, str] = {
    # ACC (Atlantic Coast Conference) - 18 women's teams
    "bc": "BC", "bostoncollege": "BC", "eagles": "BC",
    "cal": "CAL", "california": "CAL", "goldenbears": "CAL",
    "clem": "CLEM", "clemson": "CLEM", "tigers": "CLEM",
    "duke": "DUKE", "bluedevils": "DUKE",
    "fsu": "FSU", "floridastate": "FSU", "seminoles": "FSU",
    "gt": "GT", "georgiatech": "GT", "yellowjackets": "GT",
    "lou": "LOU", "louisville": "LOU", "cardinals": "LOU",
    "miami": "MIA", "miamifl": "MIA", "hurricanes": "MIA",
    "unc": "UNC", "northcarolina": "UNC", "tarheels": "UNC",
    "ncst": "NCST", "ncstate": "NCST", "wolfpack": "NCST",
    "nd": "ND", "notredame": "ND", "fightingirish": "ND",
    "pitt": "PITT", "pittsburgh": "PITT", "panthers": "PITT",
    "smu": "SMU", "mustangs": "SMU",
    "stan": "STAN", "stanford": "STAN", "cardinal": "STAN",
    "syr": "SYR", "syracuse": "SYR", "orange": "SYR",
    "uva": "UVA", "virginia": "UVA", "cavaliers": "UVA",
    "vt": "VT", "virginiatech": "VT", "hokies": "VT",
    "wake": "WAKE", "wakeforest": "WAKE", "demondeacons": "WAKE",

    # SEC (Southeastern Conference) - 16 women's teams
    "ala": "ALA", "alabama": "ALA", "crimsontide": "ALA",
    "ark": "ARK", "arkansas": "ARK", "razorbacks": "ARK",
    "aub": "AUB", "auburn": "AUB", "auburntigers": "AUB",
    "uf": "UF", "florida": "UF", "gators": "UF",
    "uga": "UGA", "georgia": "UGA", "ladybulldogs": "UGA",
    "uk": "UK", "kentucky": "UK", "ladycats": "UK", "wildcats": "UK",
    "lsu": "LSU", "louisianastate": "LSU", "ladytigers": "LSU",
    "miss": "MISS", "olemiss": "MISS", "mississippi": "MISS", "rebels": "MISS",
    "msst": "MSST", "missst": "MSST", "missstate": "MSST", "mississippistate": "MSST",
    "mizz": "MIZZ", "missouri": "MIZZ",
    "okla": "OKLA", "oklahoma": "OKLA", "sooners": "OKLA",
    "sc": "SC", "southcarolina": "SC", "gamecocks": "SC",
    "tenn": "TENN", "tennessee": "TENN", "ladyvols": "TENN", "volunteers": "TENN",
    "tex": "TEX", "texas": "TEX", "longhorns": "TEX",
    "tama": "TAMA", "texasam": "TAMA", "aggies": "TAMA",
    "vandy": "VANDY", "vanderbilt": "VANDY", "commodores": "VANDY",

    # Big Ten - 18 women's teams
    "ill": "ILL", "illinois": "ILL", "fightingillini": "ILL",
    "ind": "IND", "indiana": "IND", "hoosiers": "IND",
    "iowa": "IOWA", "hawkeyes": "IOWA",
    "md": "MD", "maryland": "MD", "terrapins": "MD", "terps": "MD",
    "mich": "MICH", "michigan": "MICH", "wolverines": "MICH",
    "msu": "MSU", "michiganstate": "MSU", "spartans": "MSU",
    "minn": "MINN", "minnesota": "MINN", "golphers": "MINN", "gophers": "MINN",
    "neb": "NEB", "nebraska": "NEB", "huskers": "NEB", "cornhuskers": "NEB",
    "nu": "NU", "northwestern": "NU",
    "osu": "OSU", "ohiostate": "OSU", "buckeyes": "OSU",
    "oregon": "ORE", "ducks": "ORE", "ore": "ORE",
    "psu": "PSU", "pennstate": "PSU", "nittanylions": "PSU",
    "pur": "PUR", "purdue": "PUR", "boilermakers": "PUR",
    "rut": "RUT", "rutgers": "RUT", "scarletknights": "RUT",
    "ucla": "UCLA", "bruins": "UCLA",
    "usc": "USC", "southerncal": "USC", "trojans": "USC",
    "wash": "WASH", "washington": "WASH", "huskies": "WASH",
    "wis": "WIS", "wisc": "WIS", "wisconsin": "WIS", "badgers": "WIS",

    # Big 12 - 16 women's teams
    "ariz": "ARIZ", "arizona": "ARIZ", "ariza": "ARIZ",
    "asu": "ASU", "arizonastate": "ASU", "sundevils": "ASU",
    "bay": "BAY", "baylor": "BAY", "ladybears": "BAY",
    "byu": "BYU", "brighamyoung": "BYU", "cougars": "BYU",
    "cin": "CIN", "cincinnati": "CIN", "bearcats": "CIN",
    "colo": "COLO", "colorado": "COLO", "buffaloes": "COLO", "buffs": "COLO",
    "hou": "HOU", "houston": "HOU", "houstoncougars": "HOU",
    "isu": "ISU", "iowastate": "ISU", "cyclones": "ISU",
    "ku": "KU", "kansas": "KU", "jayhawks": "KU",
    "ksu": "KSU", "kansasstate": "KSU", "kstate": "KSU",
    "okst": "OKST", "oklahomastate": "OKST", "cowgirls": "OKST",
    "tcu": "TCU", "texaschristian": "TCU", "hornedfrogs": "TCU",
    "ttu": "TTU", "texastech": "TTU", "ladyraiders": "TTU", "redraiders": "TTU",
    "ucf": "UCF", "centralflorida": "UCF", "knights": "UCF",
    "utah": "UTAH", "utes": "UTAH",
    "wvu": "WVU", "westvirginia": "WVU", "mountaineers": "WVU",

    # Big East - 11 women's teams
    "but": "BUT", "butler": "BUT", "butlerbulldogs": "BUT",
    "crei": "CREI", "creighton": "CREI", "bluejays": "CREI",
    "depaul": "DEP", "dep": "DEP", "bluedemons": "DEP",
    "geo": "GEO", "georgetown": "GEO", "hoyas": "GEO",
    "mar": "MAR", "marquette": "MAR", "goldeneagles": "MAR",
    "prov": "PROV", "providence": "PROV", "friars": "PROV",
    "sjf": "STJ", "stj": "STJ", "stjohns": "STJ", "redstorm": "STJ",
    "set": "SET", "setonhall": "SET", "pirates": "SET",
    "uconn": "CONN", "conn": "CONN", "connecticut": "CONN", "ladyhuskies": "CONN",
    "vill": "VILL", "villanova": "VILL", "novawildcats": "VILL",
    "xav": "XAV", "xavier": "XAV", "musketeers": "XAV",

    # AAC (American Athletic) - 14 women's teams
    "char": "CHAR", "charlotte": "CHAR", "fortyniners": "CHAR", "49ers": "CHAR",
    "ecu": "ECU", "eastcarolina": "ECU", "pirateseast": "ECU",
    "fau": "FAU", "floridaatlantic": "FAU", "owls": "FAU",
    "memph": "MEMPH", "memphis": "MEMPH",
    "navy": "NAVY", "midshipmen": "NAVY",
    "rice": "RICE", "owlsrice": "RICE",
    "smumustangs": "SMU2",
    "usf": "USF", "southflorida": "USF", "bulls": "USF",
    "temp": "TEMP", "temple": "TEMP",
    "tulane": "TUL", "greenwave": "TUL",
    "tulsa": "TULS", "goldenhurricane": "TULSA",
    "uab": "UAB", "alabamabirmingham": "UAB", "blazers": "UAB",
    "utsa": "UTSA", "texassanantonio": "UTSA", "roadrunners": "UTSA",
    "wich": "WICH", "wichita": "WICH", "wichitastate": "WICH", "shockers": "WICH",

    # Mountain West - 11 women's teams
    "afa": "AF", "airforce": "AF", "falcons": "AF",
    "bsu": "BSU", "boisestate": "BSU", "broncos": "BSU",
    "cstate": "CSU", "coloradostate": "CSU", "rams": "CSU",
    "fres": "FRES", "fresno": "FRES", "fresnostate": "FRES", "bulldogs": "FRES",
    "nev": "NEV", "nevada": "NEV", "wolfpacknev": "NEV",
    "nmsl": "NM", "newmexico": "NM", "lobos": "NM",
    "sdsu": "SDSU", "sandiegostate": "SDSU", "aztecs": "SDSU",
    "sjsu": "SJSU", "sanjosestate": "SJSU", "spartansjsu": "SJSU",
    "unlv": "UNLV", "unlasvegas": "UNLV", "runninrebels": "UNLV",
    "utst": "USU", "utahstate": "USU", "aggiesusu": "USU",
    "wyo": "WYO", "wyoming": "WYO", "wyocowgirls": "WYO",

    # MAC (Mid-American) - 12 women's teams
    "akr": "AKR", "akron": "AKR", "zips": "AKR",
    "bgsu": "BGSU", "bowlinggreen": "BGSU", "bgsufalcons": "BGSU",
    "ball": "BALL", "ballstate": "BALL", "ballstatecards": "BALL",
    "buf": "BUF", "buffalo": "BUF", "bulldogs2": "BUF",
    "cmu": "CMU", "centralmichigan": "CMU", "chippewas": "CMU",
    "emu": "EMU", "easternmichigan": "EMU", "eagles2": "EMU",
    "kent": "KENT", "kentstate": "KENT", "goldenflashes": "KENT",
    "miohio": "MOH", "miamiohio": "MOH", "redhawks": "MOH",
    "niu": "NIU", "northernillinois": "NIU", "niuhuskies": "NIU",
    "ohio": "OHIO", "bobcats": "OHIO",
    "tol": "TOL", "toledo": "TOL", "rockets2": "TOL",
    "wmu": "WMU", "westernmichigan": "WMU", "wmubroncos": "WMU",

    # Atlantic 10 - 15 women's teams
    "davids": "DAV", "davidson": "DAV", "wildcats2": "DAV",
    "day": "DAY", "dayton": "DAY", "flyers": "DAY",
    "duq": "DUQ", "duquesne": "DUQ", "dukes": "DUQ",
    "ford": "FORD", "fordham": "FORD", "fordhamrams": "FORD",
    "gmu": "GMU", "georgemason": "GMU", "patriots": "GMU",
    "gw": "GW", "georgewashington": "GW", "colonials": "GW",
    "lasalle": "LSL", "explorers": "LSL",
    "loyola": "LOY", "loyolachicago": "LOY", "ramblers": "LOY",
    "umass": "MASS", "massachusetts": "MASS", "minutewomen": "MASS",
    "rich": "RICH", "richmond": "RICH", "spiders": "RICH",
    "slu": "SLU", "stlouis": "SLU", "billikens": "SLU",
    "sbon": "SB", "stbonaventure": "SB", "bonnies": "SB",
    "stjoes": "SJU", "stjoseph": "SJU", "hawks2": "SJU",
    "vcu": "VCU", "virginiacommonwealth": "VCU", "ramsvcu": "VCU",
    "udel": "DEL", "delaware": "DEL", "delawarefightinblue": "DEL",

    # Conference USA (CUSA) - 9 women's teams
    "ftlib": "LIB", "liberty": "LIB", "flames": "LIB",
    "ftrk": "MTSU", "middletenn": "MTSU", "middletennessee": "MTSU", "blueraiders": "MTSU",
    "ftbire": "WKU", "westernkentucky": "WKU", "hilltoppers": "WKU",
    "ftcusa1": "LA", "louisianatech": "LA", "ladytechsters": "LA",
    "jvst": "JVST", "jacksonvillestate": "JVST", "ladygamecocks": "JVST",
    "nmst": "NMSU", "newmexicostate": "NMSU", "aggies2": "NMSU",
    "sam": "SHSU", "samhouston": "SHSU", "bearkats": "SHSU",
    "uts": "TXST", "texasstate": "TXST", "bobcats2": "TXST",
    "wkust": "WKU2", "ftcwh": "FIU", "floridainternational": "FIU", "panthers2": "FIU",

    # Sun Belt - 14 women's teams
    "appst": "APP", "appalachian": "APP", "appstate": "APP", "appalachianstate": "APP", "mountaineers2": "APP",
    "arst": "ARST", "arkst": "ARST", "arkansasstate": "ARST", "redwolves": "ARST",
    "ccu": "CCU", "coastalcarolina": "CCU", "chants": "CCU", "chanticleers": "CCU",
    "gasou": "GASO", "georgiasouthern": "GASO", "geosouthern": "GASO",
    "gast": "GAST", "georgiastate": "GAST", "panthers3": "GAST",
    "jmu": "JMU", "jamesmadison": "JMU", "duke3": "JMU",
    "lala": "ULL", "louisianalafayette": "ULL", "ragincajuns": "ULL",
    "ulmonroe": "ULM", "louisianamonroe": "ULM", "warhawks": "ULM",
    "marshall": "MAR2", "thunderingherd": "MAR2",
    "ode": "ODU", "oldominion": "ODU", "monarchs": "ODU",
    "sou": "SOU", "southalabama": "SOU", "jaguarssou": "SOU",
    "smiss": "USM", "southernmiss": "USM", "goldeneagles2": "USM",
    "trsu": "TROY", "troy": "TROY", "trojans2": "TROY",
    "txst2": "TXSTATE", "texstate2": "TXSTATE",

    # WCC (West Coast) - 11 women's teams
    "gonz": "GONZ", "gonzaga": "GONZ", "zags": "GONZ",
    "lmu": "LMU", "loyolamarymount": "LMU", "lions": "LMU",
    "pacif": "PAC", "pacific": "PAC", "tigers2": "PAC",
    "pep": "PEP", "pepperdine": "PEP", "waves": "PEP",
    "port": "POR", "portland": "POR", "pilots": "POR",
    "smc": "SMC", "stmarys": "SMC", "gaelssmc": "SMC",
    "sf": "SF", "sanfrancisco": "SF", "dons": "SF",
    "scu": "SCU", "santaclara": "SCU", "broncos2": "SCU",
    "sd": "SDC", "sandiego": "SDC", "toreros": "SDC",
    "byucougs": "BYUW", "wccbyu": "BYUW",
    "seattle": "SEA", "redhawks2": "SEA",

    # Big Sky - 10 women's teams
    "easstwa": "EWU", "easternwa": "EWU", "easternwashington": "EWU",
    "ida": "IDA", "idaho": "IDA", "vandals": "IDA",
    "idst": "IDST", "idahost": "IDST", "idahostate": "IDST", "bengals": "IDST",
    "mont": "MONT", "montana": "MONT", "grizzlies": "MONT",
    "monst": "MTST", "montanast": "MTST", "montanastate": "MTST", "bobcats3": "MTST",
    "naue": "NAU", "northernaz": "NAU", "lumberjacks": "NAU",
    "nco": "NCO", "ncolo": "NCO", "northerncolorado": "NCO", "bears2": "NCO",
    "psue": "PSUE", "portlandst": "PSUE", "vikings": "PSUE",
    "sue": "SAC", "sacstate": "SAC", "hornets2": "SAC",
    "wsu": "WSU", "weberstate": "WSU", "wildcats3": "WSU",

    # Big South - 9 women's teams
    "campbel": "CAMP", "campbell": "CAMP", "fightingcamels": "CAMP",
    "chsou": "CHSO", "charlestonsou": "CHSO", "charlestonsouthern": "CHSO", "buccaneers": "CHSO",
    "gar": "GAR", "gardnerwebb": "GAR", "runninbulldogs": "GAR",
    "high": "HIGH", "highpoint": "HIGH", "highpointpanthers": "HIGH",
    "long": "LONG", "longwood": "LONG", "lancers": "LONG",
    "presby": "PRES", "presbyterian": "PRES", "blueose": "PRES", "bluehose": "PRES",
    "radford": "RAD", "highlanders": "RAD",
    "uncasheville": "UNCA", "uncavl": "UNCA", "bulldogsasheville": "UNCA",
    "wincarsj": "WCU", "winthropchanced": "WCU",

    # Big West - 11 women's teams
    "csub": "CSUB", "csubakers": "CSUB", "csubakersfield": "CSUB", "roadrunners2": "CSUB",
    "csuf": "CSUF", "csufullerton": "CSUF", "csutitans": "CSUF",
    "csun": "CSUN", "csunorthridge": "CSUN", "matadors": "CSUN",
    "ham": "HAW", "hawaii": "HAW", "rainbowwahine": "HAW",
    "lbsu": "LBSU", "longbeach": "LBSU", "longbeachst": "LBSU", "thebeach": "LBSU",
    "ucd": "UCD", "ucdavis": "UCD", "ucdaggies": "UCD",
    "uci": "UCI", "ucirvine": "UCI", "anteaters": "UCI",
    "ucr": "UCR", "ucriverside": "UCR", "ucrhighlanders": "UCR",
    "ucsd": "UCSD", "ucsandiego": "UCSD", "tritons": "UCSD",
    "ucsb": "UCSB", "ucsantabarbara": "UCSB", "gauchos": "UCSB",
    "uop": "UOP", "uopacific": "UOP",

    # Colonial Athletic (CAA) - 14 women's teams
    "campbel2": "CCAA", "campbellcaa": "CCAA",
    "char2": "CHCAA", "charlestoncaa": "CHCAA", "cougars3": "CHCAA",
    "drex": "DREX", "drexel": "DREX", "dragons": "DREX",
    "elon": "ELON", "phoenix": "ELON",
    "hamp": "HAMP", "hampton": "HAMP",
    "hofstra": "HOF", "pridehof": "HOF",
    "monm": "MONM", "monmouth": "MONM", "hawks3": "MONM",
    "nce": "NCE", "ncentral": "NCE", "ncwilm": "NCWILM", "uncw": "UNCW", "seahawks": "UNCW",
    "ne": "NE", "northeastern": "NE",
    "smbo": "STO", "stonybrook": "STO", "seawolves": "STO",
    "tow": "TOW", "towson": "TOW", "towsontigers": "TOW",
    "wm": "WM", "williammary": "WM", "tribe": "WM",
    "tow2": "DREXW", "drexcaa": "DREXW",

    # Horizon League - 11 women's teams
    "clev": "CLEV", "clevelandst": "CLEV", "clevelandstate": "CLEV", "vikings2": "CLEV",
    "det": "DET2", "detroit": "DET2", "titans": "DET2",
    "gv": "GV", "greenbay": "GV", "wgreenbay": "GV", "phoenix2": "GV",
    "iuipui": "IUPUI", "iupui": "IUPUI", "jaguars2": "IUPUI",
    "milw": "MILW", "milwaukee": "MILW", "panthers4": "MILW",
    "nku": "NKU", "norkyu": "NKU", "northernky": "NKU", "norse": "NKU",
    "oak": "OAK", "oakland": "OAK", "goldengrizzlies": "OAK",
    "purdfor": "PFW", "purduefw": "PFW", "purduefortwayne": "PFW",
    "robmor": "RMU", "robertmorris": "RMU", "colonials2": "RMU",
    "wis_": "WIS_", "wright": "WRT", "wrightst": "WRT", "wrightstate": "WRT", "raiders2": "WRT",
    "ysu": "YSU", "youngstown": "YSU", "youngstownstate": "YSU", "penguins": "YSU",

    # Ivy League - 8 women's teams
    "brown": "BRWN", "brownbears": "BRWN",
    "col2": "COL2", "columbia": "COL2", "columbialions": "COL2",
    "corn": "COR", "cornell": "COR", "bigred": "COR",
    "dart": "DART", "dartmouth": "DART", "dartmothbig": "DART",
    "harv": "HARV", "harvard": "HARV", "crimson": "HARV",
    "penn": "PENN", "pennsylvania": "PENN", "quakers": "PENN",
    "prin": "PRIN", "princeton": "PRIN", "princetontigers": "PRIN",
    "yale": "YALE", "bulldogs3": "YALE",

    # MEAC (Mid-Eastern Athletic) - 8 women's teams
    "coppin": "COP", "copst": "COP", "coppinstate": "COP", "eagles3": "COP",
    "del2": "DSU", "delst": "DSU", "delawarestate": "DSU", "hornets3": "DSU",
    "howard": "HOW", "howardbison": "HOW", "bison": "HOW",
    "morganst": "MORG", "morgan": "MORG", "morganstate": "MORG", "bearsmorg": "MORG",
    "norfolk": "NORF", "norfolkst": "NORF", "norfolkstate": "NORF", "spartans2": "NORF",
    "nccarat": "NCCU", "nccentralu": "NCCU", "ncentralu": "NCCU", "eagles4": "NCCU",
    "sccst": "SCSU", "scstate": "SCSU", "scarolinast": "SCSU", "scarolinastate": "SCSU", "bulldogs4": "SCSU",
    "umes": "UMES", "marylandes": "UMES", "marylandeasternshore": "UMES", "hawks4": "UMES",

    # NEC (Northeast) - 9 women's teams
    "ccsu": "CCSU", "centralconn": "CCSU", "centralconnst": "CCSU", "centralconnecticut": "CCSU", "blue_devils2": "CCSU",
    "fdu": "FDU", "fairleighdickinson": "FDU", "knights2": "FDU",
    "hbu": "HBU", "houstonchristian": "HBU", "huskies2": "HBU",
    "leMoyne": "LEM", "lemoyne": "LEM", "dolphins": "LEM",
    "liu": "LIU", "longisland": "LIU", "sharks": "LIU",
    "merr": "MERR", "merrimack": "MERR", "warriorsmerr": "MERR",
    "sfny": "SFN", "stfrancisny": "SFN", "terriers": "SFN",
    "scred": "SCT", "saintredhawks": "SCT", "saintredhk": "SCT", "sthomas": "STH", "stthomas": "STH", "tommies": "STH",
    "wagner": "WAG", "seahawkswag": "WAG",

    # Ohio Valley (OVC) - 10 women's teams
    "ausp": "AUS", "austinpeay": "AUS", "governors": "AUS",
    "eky": "EKU", "easternkentucky": "EKU", "colonels": "EKU",
    "eill": "EIU", "easternillinois": "EIU", "panthers5": "EIU",
    "lind": "LIND", "lindenwood": "LIND", "lynx2": "LIND",
    "morhd": "MOR", "moreheadst": "MOR", "moreheadstate": "MOR", "eagles5": "MOR",
    "siue": "SIUE", "siedwardsville": "SIUE", "sillinoisedwardsville": "SIUE",
    "semo": "SEMO", "southeastmissouri": "SEMO", "redhawks2": "SEMO",
    "tnst": "TNST", "tennst": "TNST", "tennesseestate": "TNST", "lady_tigersst": "TNST",
    "tntech": "TNT", "tenntech": "TNT", "tennesseetech": "TNT", "goldeneagles3": "TNT",
    "umsl": "UMSL", "morrisstate": "UMSL", "uttymartin": "UTM", "uttenneessemartin": "UTM", "skyhawks": "UTM",

    # Patriot League - 10 women's teams
    "amer": "AMER", "american": "AMER", "americaneagles": "AMER",
    "armywp": "ARMY", "army": "ARMY", "blackknights": "ARMY",
    "bk": "BUCK", "bucknell": "BUCK", "bisonbk": "BUCK",
    "boston2": "BOS2", "bostonu": "BOS2", "bostonuniversity": "BOS2", "terrierboston": "BOS2",
    "colg": "COLG", "colgate": "COLG", "raidersclg": "COLG",
    "hcr": "HC", "holycross": "HC", "crusaders": "HC",
    "lafay": "LAF", "lafayette": "LAF", "leopards": "LAF",
    "leh": "LEH", "lehigh": "LEH", "mountainhawks": "LEH",
    "lyola": "LOY2", "loyolamd": "LOY2", "greyhounds": "LOY2",
    "navy2": "NAV", "midshipmen2": "NAV",

    # SoCon (Southern Conference) - 10 women's teams
    "cit": "CIT", "citadel": "CIT", "bulldogs5": "CIT",
    "chat": "CHA", "chattanooga": "CHA", "mocs": "CHA",
    "etsu": "ETSU", "easttennst": "ETSU", "easttennesseestate": "ETSU", "buccaneers2": "ETSU",
    "furman": "FUR", "paladins": "FUR",
    "mer": "MER", "mercer": "MER",
    "samford": "SAM", "samfordbulldogs": "SAM",
    "uncg": "UNCG", "ncgreensboro": "UNCG", "ncarolinagreensboro": "UNCG", "spartans3": "UNCG",
    "vmi": "VMI", "keydets": "VMI",
    "wofford": "WOF", "terriers2": "WOF",
    "wcu": "WCU2", "westcarolina": "WCU2", "westerncarolina": "WCU2", "catamounts": "WCU2",

    # Southland - 9 women's teams
    "hcu": "HCU", "houstonchrist": "HCU",
    "incw": "INCW", "incwordcr": "INCW", "incarnateword": "INCW", "cardinals2": "INCW",
    "lit": "LIT", "lamar": "LIT", "cards": "LIT",
    "mcneese": "MCN", "cowboys": "MCN",
    "nicholls": "NICH", "colonels2": "NICH",
    "northwestst": "NWS", "northwesternst": "NWS", "demons": "NWS",
    "norld": "NO", "neworleans": "NO", "privateers": "NO",
    "selastate": "SELA", "southeastlast": "SELA", "southeasternlouisiana": "SELA", "lions2": "SELA",
    "tamuc": "TAMUC", "texasamcommerce": "TAMUC",

    # Summit League - 9 women's teams
    "denver": "DEN", "denverpioneers": "DEN", "pioneersdu": "DEN",
    "ndst": "NDSU", "ndstate": "NDSU", "northdakotastate": "NDSU", "bisonndst": "NDSU",
    "noddakn": "ND2", "north_dak": "ND2", "northdakota": "ND2", "fightinghawks": "ND2",
    "omaha": "OMA", "neomaha": "OMA", "mavericksomaha": "OMA",
    "orl": "ORLR", "oralroberts": "ORLR", "goldeneagles4": "ORLR",
    "stthomas2": "ST2", "stthomasmn": "ST2",
    "sdst": "SDS", "sdstate": "SDS", "southdakotastate": "SDS", "jackrabbits": "SDS",
    "sd2": "SD", "southdakota": "SD", "coyotes": "SD",
    "kc": "KC", "kansascity": "KC", "rooskc": "KC", "roos": "KC",

    # SWAC (Southwestern Athletic) - 12 women's teams
    "alast": "ALST", "alabamast": "ALST", "alabamastate": "ALST", "hornets4": "ALST",
    "alcorn": "ALCN", "alcornst": "ALCN", "alcornstate": "ALCN", "bravesalcorn": "ALCN",
    "alabamamb": "AAMU", "alabamaamu": "AAMU", "bulldogs6": "AAMU",
    "ark_pb": "UAPB", "arkansaspb": "UAPB", "arkansaspinebluff": "UAPB", "lionsuapb": "UAPB",
    "bcc": "BCU", "bethunecookman": "BCU", "wildcats4": "BCU",
    "famu": "FAMU", "floridaamu": "FAMU", "rattlers": "FAMU",
    "gram": "GRAM", "grambling": "GRAM", "gramblingst": "GRAM", "tigers3": "GRAM",
    "jackson_st": "JKST", "jacksonst": "JKST", "jacksonstate": "JKST", "tigers4": "JKST",
    "msvst": "MVSU", "miss_valley": "MVSU", "mississippivalley": "MVSU", "delta_devils": "MVSU",
    "prairieview": "PV", "pvamu": "PV", "panthers6": "PV",
    "subr": "SUBR", "southernu": "SUBR", "southernuniversity": "SUBR", "jaguars2sub": "SUBR",
    "tsu": "TXSU", "texasso": "TXSU", "texassouthern": "TXSU", "tigers5": "TXSU",

    # WAC (Western Athletic) - 11 women's teams
    "abch": "ABCH", "abchristian": "ABCH", "abilenechristian": "ABCH", "wildcats5": "ABCH",
    "cbu": "CBU", "californiabap": "CBU", "californiabaptist": "CBU", "lancersb": "CBU",
    "gv2": "GCU", "grandcanyon": "GCU", "antelopes": "GCU",
    "ssmary": "SMU3", "stmaryswac": "SMU3",
    "stf": "STF", "stephenf": "STF", "stephenfaustin": "STF", "ladyjacks": "STF", "lumberjacks2": "STF",
    "tarleton": "TAR", "texans": "TAR",
    "uca": "UCA", "centralarkansas": "UCA", "sugar_bears": "UCA", "sugarbears": "UCA",
    "utah_tech": "UT", "utahtech": "UT", "trailblazers": "UT",
    "uta": "UTAW", "utarlington": "UTAW", "mavericksta": "UTAW",
    "utrgv": "UTRGV", "utexrgv": "UTRGV", "utriograndevalley": "UTRGV", "vaqueros": "UTRGV",
    "uvu": "UVU", "utahvalley": "UVU", "wolverines2": "UVU",

    # ASUN (A-Sun) - 12 women's teams
    "austin": "AP", "austinpb": "AP",
    "bell": "BEL", "bellarmine": "BEL", "knights3": "BEL",
    "centarkst": "CARK", "centarkansas": "CARK", "centralark": "CARK",
    "etrkst": "ETSU2",
    "ehilill": "ESH", "eshillhillcrest": "ESH",
    "fgcu": "FGCU", "florida_gulf": "FGCU", "floridagulfcoast": "FGCU", "eagles6": "FGCU",
    "ftbn": "FBNU", "fbynnk": "FBNU",
    "jax_": "JAX", "jacksonville": "JAX", "dolphins2": "JAX",
    "jville_st": "JAXS",
    "kennest": "KSU2", "kennesawst": "KSU2", "kennesawstate": "KSU2", "owls2": "KSU2",
    "lipscomb": "LIP", "bisonsl": "LIP",
    "nflorida": "UNF", "northflorida": "UNF", "ospreys": "UNF",
    "queens": "QUEENS", "queensnc": "QUEENS", "queenscarolina": "QUEENS",
    "stetson": "STET", "hatters": "STET",
    "uwg": "UWG", "westgeorgia": "UWG", "wolves2": "UWG",

    # Northeast / MAAC - additional women's teams (MAAC ~11 teams)
    "canisius": "CAN", "goldengriffins": "CAN", "griffs": "CAN",
    "fairf": "FAIR", "fairfield": "FAIR", "stagsf": "FAIR",
    "iona": "IONA", "gaels": "IONA",
    "manhat": "MAN", "manhattan": "MAN", "jaspers": "MAN",
    "marist": "MARIST", "redfoxes": "MARIST",
    "monm2": "MON2", "monmouthmaac": "MON2",
    "mount": "MSM", "mtstmary": "MSM", "mountsaintmarys": "MSM", "mountaineers3": "MSM",
    "niag": "NIAG", "niagara": "NIAG", "purpleeagles": "NIAG",
    "qu": "QPC", "quinn": "QPC", "quinnipiac": "QPC", "bobcats4": "QPC",
    "rider": "RID", "broncs": "RID",
    "siena": "SIE", "saints": "SIE",

    # Southland additions & misc independents
    "bell2": "BELC", "bellarcal": "BELC", "bellarmineind": "BELC",
    "chic": "CSC", "chicagost": "CSC", "chicagostate": "CSC",
    "njit": "NJIT", "newjerseytech": "NJIT", "highlanders2": "NJIT",
    "saintfran": "SFI", "stfrancisin": "SFI", "stfrancispa": "SFP", "redflash": "SFP",
    "stbon2": "STB2", "stbonaventure2": "STB2",
    "vmh": "VMI2",

    # Independents and unique programs not in the above
    "uic": "UIC", "illchicago": "UIC", "illinoischicago": "UIC", "flames2": "UIC",
    "csaramento": "SAC2", "sacstate2": "SAC2",
    "evans": "EVAN", "evansville": "EVAN", "purpleaces": "EVAN",
    "udayton": "DAY2", "daytonwomen": "DAY2",
    "wofford2": "WOF2",
    "morris": "MOR2", "morris_st": "MOR2",
    "centarknst": "CARS",

    # MVC (Missouri Valley Conference) - 12 women's teams
    "brad": "BRAD", "bradley": "BRAD", "bradleybraves": "BRAD",
    "bel": "BEL2", "belmont": "BEL2", "belmontbruins": "BEL2",
    "drak": "DRAKE", "drake": "DRAKE", "drakebulldogs": "DRAKE",
    "evansv": "EVA2", "evansville2": "EVA2", "purpleaces2": "EVA2",
    "ilstu": "ILSU", "illinoisst": "ILSU", "illinoisstate": "ILSU", "redbirds": "ILSU",
    "indst": "INST", "indianast": "INST", "indianastate": "INST", "sycamores": "INST",
    "mursta": "MUR", "murrayst": "MUR", "murraystate": "MUR", "racers": "MUR",
    "ncolombia": "MIZZ2",
    "niu_mvc": "NIU2",
    "ucwm": "UCM", "centralmissouri": "UCM",
    "uniow": "UNI", "northerniowa": "UNI", "uniowapanthers": "UNI",
    "valpo": "VAL", "valparaiso": "VAL", "beacons": "VAL",
}
